services:
    misuzu:
        build:
            context: ./misuzu
            dockerfile: Dockerfile
        ports:
            - "3333:8000"
        command:
            php artisan serve --host=0.0.0.0
        volumes:
            - ./misuzu:/var/www/html
