services:
    konata:
        build: ./konata
        restart: always
        ports:
         - "443:443"
        volumes:
         - ./konata/conf.d/:/etc/nginx/conf.d
         - ./konata/ssl/:/etc/nginx/ssl
        environment:
            - APP_DOMAIN=$APP_DOMAIN
        depends_on:
         - haruhi
         - eru
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        restart: always
        hostname: haruhi
        environment:
            - APP_ENV=$APP_ENV
            - APP_DEBUG=$APP_DEBUG
            - APP_URL=$APP_URL
            - APP_DOMAIN=$APP_DOMAIN
            - APP_KEY=$APP_KEY
            - DB_HOST=$DB_HOST
            - DB_DATABASE=$DB_DATABASE
            - DB_USERNAME=$DB_MIDAS_API_USER
            - DB_PASSWORD=$DB_MIDAS_API_PASSWORD
            - SANCTUM_STATEFUL_DOMAINS=$APP_DOMAIN
            - SESSION_DOMAIN=$APP_DOMAIN
        volumes:
            - ./haruhi:/var/www/html
    eru:
        build:
            context: ./eru
            dockerfile: Dockerfile
        restart: always
        environment:
            - MB_DB_TYPE=mysql
            - MB_DB_DBNAME=$DB_METABASE_DATABASE
            - MB_DB_PORT=3306
            - MB_DB_USER=$DB_METABASE_ROOT_USER
            - MB_DB_PASS=$DB_METABASE_ROOT_PASSWORD
            - MB_DB_HOST=$DB_HOST
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_CHARSET=$DB_DATABASE_CHARSET
            - MYSQL_COLLATION=$DB_DATABASE_COLLATION
            - MYSQL_USER=$DB_MIDAS_ROOT_USER
            - MYSQL_PASSWORD=$DB_MIDAS_ROOT_PASSWORD
            - DB_MIDAS_API_USER=$DB_MIDAS_API_USER
            - DB_MIDAS_API_PASSWORD=$DB_MIDAS_API_PASSWORD
            - DB_MIDAS_ANALYZE_USER=$DB_MIDAS_ANALYZE_USER
            - DB_MIDAS_ANALYZE_PASSWORD=$DB_MIDAS_ANALYZE_PASSWORD
            - DB_METABASE_DATABASE=$DB_METABASE_DATABASE
            - DB_METABASE_ROOT_USER=$DB_METABASE_ROOT_USER
            - DB_METABASE_ROOT_PASSWORD=$DB_METABASE_ROOT_PASSWORD
            - DB_TASK_USER=$DB_TASK_USER
            - DB_TASK_PASSWORD=$DB_TASK_PASSWORD
        hostname: yui
        volumes:
            - ./yui/initdb.d:/docker-entrypoint-initdb.d
            - db:/var/lib/mysql
    rikka:
        build: ./rikka
        restart: always
        environment:
            - NAS_PATH=$NAS_PATH
            - NAS_USER=$NAS_USER
            - NAS_PASS=$NAS_PASS
            - DB_TASK_USER=$DB_TASK_USER
            - DB_TASK_PASS=$DB_TASK_PASSWORD
            - DB_HOST=$DB_HOST
            - DB_MIDAS_DATABASE_NAME=$DB_DATABASE
            - DB_METABASE_DATABASE_NAME=$DB_METABASE_DATABASE
            - ENCRYPTION_KEY=$ENCRYPTION_KEY
            - DISCORD_URL=$DISCORD_URL
        volumes:
         - ./rikka:/app
        privileged: true
        tty: true
    azusa:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=midas
            - MYSQL_CHARSET=$DB_DATABASE_CHARSET
            - MYSQL_COLLATION=$DB_DATABASE_COLLATION
            - MYSQL_USER=midas
            - MYSQL_PASSWORD=midaspass
            - DB_MIDAS_API_USER=$DB_MIDAS_API_USER
            - DB_MIDAS_API_PASSWORD=$DB_MIDAS_API_PASSWORD
        hostname: azusa
        volumes:
            - ./azusa/initdb.d:/docker-entrypoint-initdb.d
volumes:
    db:

