services:
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        volumes:
            - ./haruhi:/var/www/html
    azusa:
        build:
            context: ./yui
            dockerfile: Dockerfile
