version: '3.3'
services:
    konata:
        build: ./konata
        ports:
         - "443:443"
        volumes:
         - ./konata/conf.d/:/etc/nginx/conf.d
         - ./konata/ssl/:/etc/nginx/ssl
        depends_on:
         - haruhi
         - eru
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        restart: always
        hostname: haruhi
        # command: npm run watch
        volumes:
            - ./haruhi:/var/www/html
    eru:
        build:
            context: ./eru
            dockerfile: Dockerfile
        restart: always
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
            - MB_SITE_URL="http://midas.home.arpa:3000/eru"
        volumes:
            - ./eru/metabase:/metabase-data
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        env_file: ./yui/.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    rikka:
        build: ./rikka
        restart: always
        env_file: ./rikka/.env
        volumes:
         - ./rikka:/home/root
        privileged: true
        tty: true
volumes:
    db:

