version: '3.3'
services:
    konata:
        build: ./konata
        ports:
         - "443:443"
        volumes:
         - ./konata/conf.d/:/etc/nginx/conf.d
         - ./konata/ssl/:/etc/nginx/ssl
        depends_on:
         - haruhi
         - eru
    haruhi:
        build:
            context: ./haruhi
            dockerfile: Dockerfile
        restart: always
        hostname: haruhi
        # command: npm run watch
        environment:
            - DB_HOST=$DB_HOST
            - DB_DATABASE=$DB_DATABASE
            - DB_USERNAME=$DB_MIDAS_API_USER
            - DB_PASSWORD=$DB_MIDAS_API_PASSWORD
        volumes:
            - ./haruhi:/var/www/html
    eru:
        build:
            context: ./eru
            dockerfile: Dockerfile
        restart: always
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
            - MB_SITE_URL="http://midas.home.arpa:3000/eru"
        volumes:
            - ./eru/metabase:/metabase-data
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_CHARSET=$DB_DATABASE_CHARSET
            - MYSQL_COLLATION=$DB_DATABASE_COLLATION
            - MYSQL_USER=$DB_MIDAS_ROOT_USER
            - MYSQL_PASSWORD=$DB_MIDAS_ROOT_PASSWORD
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    rikka:
        build: ./rikka
        restart: always
        environment:
            - NAS_PATH=$NAS_PATH
            - NAS_USER=$NAS_USER
            - NAS_PASS=$NAS_PASS
            - DB_MIDAS_ROOT_USER=$DB_MIDAS_ROOT_USER
            - DB_MIDAS_ROOT_PASS=$DB_MIDAS_ROOT_PASSWORD
            - DB_MIDAS_BACKUP_USER=$DB_MIDAS_BACKUP_USER
            - DB_MIDAS_BACKUP_PASS=$DB_MIDAS_BACKUP_PASSWORD
            - DB_HOST=$DB_HOST
            - DB_DATABASE_NAME=$DB_DATABASE
            - ENCRYPTION_KEY=$ENCRYPTION_KEY
            - SLACK_URL=$SLACK_URL
            - SLACK_USER=$SLACK_USER
        volumes:
         - ./rikka:/home/root
        privileged: true
        tty: true
volumes:
    db:

