#!/bin/sh

mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_MIDAS_API_USER}@'%' IDENTIFIED BY '${DB_MIDAS_API_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_MIDAS_ANALYZE_USER}@'%' IDENTIFIED BY '${DB_MIDAS_ANALYZE_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT GRANT OPTION ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'%';"

mysql -u ${MYSQL_USER} -h 127.0.0.1 -p${MYSQL_PASSWORD} -e"GRANT ALL ON ${MYSQL_DATABASE}.* TO ${DB_MIDAS_API_USER}@'%';"
mysql -u ${MYSQL_USER} -h 127.0.0.1 -p${MYSQL_PASSWORD} -e"GRANT SELECT ON ${MYSQL_DATABASE}.* TO ${DB_MIDAS_ANALYZE_USER}@'%';"
