#!/bin/sh

mariadb -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE DATABASE ${DB_METABASE_DATABASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
mariadb -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${DB_METABASE_ROOT_USER}@'%' IDENTIFIED BY '${DB_METABASE_ROOT_PASSWORD}';"
mariadb -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT ALL ON ${DB_METABASE_DATABASE}.* TO ${DB_METABASE_ROOT_USER}@'%';"
mariadb -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT GRANT OPTION ON ${DB_METABASE_DATABASE}.* TO ${DB_METABASE_ROOT_USER}@'%';"
