on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord (start)
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "[${{ inputs.name }}] build start"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/midas-bocchi-${{ inputs.name }}:latest
          file: ${{ inputs.name }}/DockerfileProduction
          platforms: linux/arm/v7
      - name: Notify Discord (success)
        if: ${{ success() }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "[${{ inputs.name }}] build successed"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Notify Discord (fail)
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "[${{ inputs.name }}] build failed"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
