name: nagisa image build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "nagisa/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: elm download
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          mv elm /usr/local/bin/
      - name: build file
        run: |
          pwd
          ls -al
          cd nagisa
          elm make src/Main.elm --output=../dist/main.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-test
          path: dist/**
