name: eru image build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "eru/**"

jobs:
  plan:
    uses: firedial/midas-bocchi/.github/workflows/build_common.yaml@main
    with:
      name: eru
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
