name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  notify-start:
    uses: firedial/midas-bocchi/.github/workflows/notify.yaml@main
    with:
      message: |
        build start
        ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  build-konata:
    needs: notify-start
    uses: firedial/midas-bocchi/.github/workflows/docker_build.yaml@main
    with:
      name: konata
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-haruhi:
    needs: notify-start
    uses: firedial/midas-bocchi/.github/workflows/docker_build.yaml@main
    with:
      name: haruhi
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-eru:
    needs: notify-start
    uses: firedial/midas-bocchi/.github/workflows/docker_build.yaml@main
    with:
      name: eru
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-rikka:
    needs: notify-start
    uses: firedial/midas-bocchi/.github/workflows/docker_build.yaml@main
    with:
      name: rikka
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-yui:
    needs: notify-start
    uses: firedial/midas-bocchi/.github/workflows/docker_build.yaml@main
    with:
      name: yui
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  url-test:
    needs: build-haruhi
    uses: firedial/midas-bocchi/.github/workflows/url_test.yaml@main

  notify-success:
    needs: [url-test, build-eru, build-konata, build-rikka, build-yui]
    if: ${{ success() }}
    uses: firedial/midas-bocchi/.github/workflows/notify.yaml@main
    with:
      message: |
        build successed
        konata: ${{ needs.build-konata.outputs.display }}
        haruhi: ${{ needs.build-haruhi.outputs.display }}
        eru: ${{ needs.build-eru.outputs.display }}
        rikka: ${{ needs.build-rikka.outputs.display }}
        yui: ${{ needs.build-yui.outputs.display }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  notify-failure:
    needs: [url-test, build-eru, build-konata, build-rikka, build-yui]
    if: ${{ failure() }}
    uses: firedial/midas-bocchi/.github/workflows/notify.yaml@main
    with:
      message: "build failed"
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
