name: url test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  url:
    runs-on: ubuntu-24.04-arm
    env:
      COMPOSE_FILE: compose.test.base.yaml:compose.test.ci.yaml
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d --wait
      - run: chmod -R 777 ./haruhi/storage
      - run: docker compose exec -T haruhi composer install
      - run: docker compose exec -T tamako php /app/main.php
